using System.Collections;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Text.RegularExpressions;
using FluentAssertions;

namespace SentenceStudio.UnitTests.Resources;

/// <summary>
/// Repo-wide localization parity for <c>AppResources</c>. Deliberately not scoped to one feature:
/// a missing translation or a mismatched placeholder is the same defect wherever it appears.
/// </summary>
/// <remarks>
/// <para>
/// Two of these checks run against a recorded baseline rather than at zero. When this test was
/// written the neutral file already had 62 keys with no Korean translation and 25 keys carrying
/// emoji, all of it predating the test and belonging to features outside its author's lane.
/// Asserting zero would have meant either failing the build on day one or deleting the test.
/// </para>
/// <para>
/// The baselines are therefore <b>ceilings, not permissions</b>: the assertions are subset
/// checks, so any NEW untranslated key or NEW emoji fails immediately, while paying down the
/// existing debt keeps the test green. Entries may be pruned from the baselines as they are
/// fixed; a stale entry is harmless but should not be left forever.
/// </para>
/// <para>
/// Everything else — keys present only in Korean, placeholder agreement, empty values — is held
/// at zero, because there is currently no debt there and none should be introduced.
/// </para>
/// </remarks>
public class ResourceParityTests
{
    private static readonly CultureInfo Neutral = CultureInfo.InvariantCulture;
    private static readonly CultureInfo Korean = new("ko");

    private static readonly Regex PlaceholderPattern = new(@"\{(\d+)\}", RegexOptions.Compiled);

    /// <summary>
    /// Emoji, dingbats and variation selectors. The project rule is Bootstrap Icons only.
    /// </summary>
    private static readonly Regex EmojiPattern =
        new(@"[\uD800-\uDBFF][\uDC00-\uDFFF]|[\u2600-\u27BF\uFE0F]", RegexOptions.Compiled);

    /// <summary>
    /// Keys with no Korean translation when this test was introduced (2026-08-15). Ceiling only.
    /// </summary>
    private static readonly HashSet<string> KnownUntranslated = new(StringComparer.Ordinal)
    {
        "ActivityCompleteLabel", "ActivityProgressTitle", "BulkAddVocabulary", "ColonDelimiter",
        "CommaDelimiter", "DashboardTitle", "EnterVocabularyPairs", "Error",
        "FailedToImportVocabulary", "Format", "HideNativeWords", "HyphenDelimiter",
        "ImportComplete", "ImportFromFile", "ImportVocabulary", "ModeChooseOwn", "ModeTodaysPlan",
        "No Vocabulary", "NoValidVocabularyFound", "NoVocabularyToImport", "PlanCardTitle",
        "PlanChooseOwnButton", "PlanCompleteLabel", "PlanItemClozeDesc", "PlanItemClozeTitle",
        "PlanItemConversationDesc", "PlanItemConversationTitle", "PlanItemListeningDesc",
        "PlanItemListeningTitle", "PlanItemReadingDesc", "PlanItemReadingTitle",
        "PlanItemShadowingDesc", "PlanItemShadowingTitle", "PlanItemTranslationDesc",
        "PlanItemTranslationTitle", "PlanItemVideoDesc", "PlanItemVideoTitle",
        "PlanItemVocabGameDesc", "PlanItemVocabGameTitle", "PlanItemVocabReviewDesc",
        "PlanItemVocabReviewTitle", "PlanMinAbbrev", "PlanMinutesLabel", "PlanRegenerateButton",
        "PlanResumeButton", "PlanSequentialHint", "PlanStartButton", "PlanSummary_Freeform",
        "PlanWordsLabel", "RoundsLabel", "SelectFile", "ShowAllWords", "TabDelimiter",
        "TapTargetToReveal", "This resource has no vocabulary to study.", "TitleRequired",
        "UploadFile", "ValidationError", "VocabularyImportSuccess",
        "VocabularyImportWithDuplicates", "VocabularyQuiz", "VocabularyWords"
    };

    /// <summary>
    /// Keys carrying emoji when this test was introduced (2026-08-15). Ceiling only.
    /// </summary>
    private static readonly HashSet<string> KnownEmoji = new(StringComparer.Ordinal)
    {
        "AllVocabularyCompleted", "AllVocabularyCompletedInQuiz",
        "AllVocabularyCompletedInQuizShort", "AllWordsCompletedAddingNew", "AutoGenerated",
        "Congratulations", "CorrectWithStreak", "FuzzyMatchCorrect", "GreatMatch",
        "IncorrectStreakReset", "Manual", "MasteredWithStreak", "Orphaned",
        "PolishingTranscriptWithAI", "ResourceCount", "RoundStarted", "RoundTimeForTyping",
        "SessionComplete", "SessionPerformance", "SessionResults", "StreakDisplay",
        "TodaysVocabularyReview", "WordMasteredInQuiz", "WordMasteredNewAdded",
        "WordsMasteredNewAdded"
    };

    // ---------------------------------------------------------------- parity

    [Fact]
    public void NoNewKeyIsLeftUntranslated()
    {
        var untranslated = Strings(Neutral).Keys
            .Except(Strings(Korean).Keys, StringComparer.Ordinal)
            .Except(KnownUntranslated, StringComparer.Ordinal)
            .OrderBy(k => k, StringComparer.Ordinal)
            .ToList();

        untranslated.Should().BeEmpty(
            "every new string must ship translated; add the Korean value rather than the key to the baseline");
    }

    [Fact]
    public void NoKeyExistsOnlyInKorean()
    {
        // A Korean-only key is always a mistake: a rename or deletion that missed one file.
        var orphaned = Strings(Korean).Keys
            .Except(Strings(Neutral).Keys, StringComparer.Ordinal)
            .OrderBy(k => k, StringComparer.Ordinal)
            .ToList();

        orphaned.Should().BeEmpty();
    }

    [Fact]
    public void PlaceholdersAgreeAcrossCultures()
    {
        var english = Strings(Neutral);
        var korean = Strings(Korean);

        var mismatched = english
            .Where(pair => korean.ContainsKey(pair.Key))
            .Where(pair => !Placeholders(pair.Value).SetEquals(Placeholders(korean[pair.Key])))
            .Select(pair => pair.Key)
            .OrderBy(k => k, StringComparer.Ordinal)
            .ToList();

        // Korean reorders arguments freely, so the SET of indices is what must match. A missing
        // or extra index is a FormatException the moment that string renders.
        mismatched.Should().BeEmpty();
    }

    [Fact]
    public void PlaceholderIndicesAreContiguousFromZero()
    {
        foreach (var culture in new[] { Neutral, Korean })
        {
            var broken = Strings(culture)
                .Where(pair => Placeholders(pair.Value).Count > 0)
                .Where(pair => !Placeholders(pair.Value).SetEquals(
                    Enumerable.Range(0, Placeholders(pair.Value).Count).ToHashSet()))
                .Select(pair => pair.Key)
                .OrderBy(k => k, StringComparer.Ordinal)
                .ToList();

            broken.Should().BeEmpty($"a skipped format argument throws at runtime in '{culture.Name}'");
        }
    }

    [Fact]
    public void NoValueIsEmpty()
    {
        foreach (var culture in new[] { Neutral, Korean })
        {
            var blank = Strings(culture)
                .Where(pair => string.IsNullOrWhiteSpace(pair.Value))
                .Select(pair => pair.Key)
                .OrderBy(k => k, StringComparer.Ordinal)
                .ToList();

            blank.Should().BeEmpty($"a blank value renders as empty UI in '{culture.Name}'");
        }
    }

    [Fact]
    public void NoNewStringUsesEmoji()
    {
        var offenders = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var culture in new[] { Neutral, Korean })
        {
            foreach (var pair in Strings(culture))
            {
                if (EmojiPattern.IsMatch(pair.Value) && !KnownEmoji.Contains(pair.Key))
                {
                    offenders.Add(pair.Key);
                }
            }
        }

        offenders.Should().BeEmpty("iconography is Bootstrap Icons only; use bi-* instead of an emoji");
    }

    // ---------------------------------------------------------------- plumbing

    /// <summary>
    /// AppResources is internal to SentenceStudio.Shared, so the ResourceManager is reached by
    /// reflection rather than by widening its visibility for a test.
    /// </summary>
    private static ResourceManager ResourceManager
    {
        get
        {
            var type = typeof(LocalizationManager).Assembly
                .GetType("SentenceStudio.Resources.Strings.AppResources", throwOnError: true)!;

            var property = type.GetProperty("ResourceManager",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)!;

            return (ResourceManager)property.GetValue(null)!;
        }
    }

    private static Dictionary<string, string> Strings(CultureInfo culture)
    {
        // tryParents: false so a key present only in the neutral file cannot masquerade as
        // translated — which is precisely what a parity test has to catch.
        var set = ResourceManager.GetResourceSet(culture, createIfNotExists: true, tryParents: false);
        set.Should().NotBeNull($"the resource set for '{culture.Name}' must ship");

        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (DictionaryEntry entry in set!)
        {
            if (entry.Key is string key && entry.Value is string value)
            {
                result[key] = value;
            }
        }

        return result;
    }

    private static HashSet<int> Placeholders(string value) => PlaceholderPattern
        .Matches(value)
        .Select(m => int.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture))
        .ToHashSet();
}
