using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace SentenceStudio.Shared.Models;

/// <summary>
/// Parent row for a user's daily plan on a given local calendar date. Owns
/// the language-neutral facts (<see cref="RationaleFacts"/>,
/// <see cref="NarrativeFacts"/>) and the generation metadata (Strategy,
/// GeneratedAtUtc). Child rows live in <see cref="DailyPlanCompletion"/>.
///
/// One row per (UserProfileId, Date). The Date column stores the user's
/// local calendar date — never UTC. Plan code reads "today" exclusively
/// through <c>IPlanDateContext.UserLocalDate</c>.
///
/// Synced via CoreSync alongside <see cref="DailyPlanCompletion"/>. PK is a
/// deterministic string (GUID-like) generated by the server / app so HTTP and
/// CoreSync inserts collide on the same primary key when they describe the
/// same logical plan.
/// </summary>
[Table("DailyPlan")]
public class DailyPlan
{
    public string Id { get; set; } = string.Empty;

    public string UserProfileId { get; set; } = string.Empty;

    /// <summary>
    /// User-local calendar date this plan is for, stored as a UTC instant
    /// at midnight of the user's local day (e.g. 2026-05-16 00:00:00Z).
    /// This matches <see cref="DailyPlanCompletion.Date"/>'s convention and
    /// keeps CoreSync's column-type expectations consistent across providers.
    /// Compute the value via
    /// <c>IPlanDateContext.UserLocalDate.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc)</c>
    /// — never read <see cref="DateTime.UtcNow"/>.<c>Date</c> directly.
    /// DTOs at the API edge expose this as <see cref="DateOnly"/>.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// UTC instant the plan was generated. Distinct from
    /// <see cref="DailyPlanCompletion.CompletedAt"/> on items.
    /// </summary>
    public DateTime GeneratedAtUtc { get; set; }

    /// <summary>
    /// Generation strategy used: <c>deterministic</c> or <c>llm</c>. v1 always
    /// stores <c>deterministic</c> since the LLM path is not wired up.
    /// </summary>
    public string Strategy { get; set; } = string.Empty;

    /// <summary>
    /// Language-neutral rationale facts as JSON. The API edge expands these
    /// into a localized <c>Rationale</c> string per <c>Accept-Language</c>.
    /// Nullable for forward compatibility (older clients may write plans
    /// without rationale facts).
    /// </summary>
    public string? RationaleFacts { get; set; }

    /// <summary>
    /// Language-neutral narrative facts (story arc, focus areas, resource
    /// summaries, vocab insights, tag insights) as JSON. The API edge
    /// inflates these into the localized <c>PlanNarrativeDto</c>.
    /// </summary>
    public string? NarrativeFacts { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
