namespace SentenceStudio.Shared.Models;

/// <summary>
/// Where an example/reference sentence originated.
/// </summary>
public enum ExampleSentenceSource
{
    /// <summary>Provenance not recorded (legacy/imported content).</summary>
    Unknown = 0,

    /// <summary>Generated by AI as a starter suggestion.</summary>
    AiGenerated = 1,

    /// <summary>Written by the learner.</summary>
    UserAuthored = 2,

    /// <summary>Captured from a reading/learning resource the learner encountered.</summary>
    FromReading = 3,
}

/// <summary>
/// Curation state of an example sentence. Only <see cref="Curated"/> and
/// <see cref="Verified"/> sentences are eligible to feed quizzes/review.
/// </summary>
public enum ExampleSentenceStatus
{
    /// <summary>AI draft the learner has not yet kept/edited. NOT quiz-eligible.</summary>
    Suggested = 0,

    /// <summary>Learner kept, edited, or authored it. Quiz-eligible.</summary>
    Curated = 1,

    /// <summary>Explicitly verified as high quality. Quiz-eligible.</summary>
    Verified = 2,
}

/// <summary>
/// Korean speech level / register of a sentence. First-class metadata so reviews
/// can be matched to the learner's target register and AI generation constrained.
/// </summary>
public enum SpeechRegister
{
    /// <summary>Register not specified.</summary>
    Unspecified = 0,

    /// <summary>합쇼체 — formal polite (deferential).</summary>
    FormalPolite = 1,

    /// <summary>해요체 — informal polite (everyday courteous).</summary>
    InformalPolite = 2,

    /// <summary>반말 / 해체 — casual / intimate.</summary>
    Casual = 3,

    /// <summary>한다체 — plain / written / declarative.</summary>
    PlainWritten = 4,
}
