// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SentenceStudio.Api.Coach.Persistence;

#nullable disable

namespace SentenceStudio.Api.Coach.Persistence.Migrations
{
    [DbContext(typeof(CoachDbContext))]
    [Migration("20260815030125_InitialCoachSchema")]
    partial class InitialCoachSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SentenceStudio.Api.Coach.Persistence.CoachPlanRevision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AcceptedConstraintDeltaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AfterPlanHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AfterPlanSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AfterPlanVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BeforePlanHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BeforePlanSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforePlanVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentKind")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUndone")
                        .HasColumnType("boolean");

                    b.Property<int>("PreservedCompletedCount")
                        .HasColumnType("integer");

                    b.Property<int>("PreservedInProgressCount")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UndoneByRevisionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CoachPlanRevision_CreatedAt");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_CoachPlanRevision_UserProfileId");

                    b.HasIndex("UserProfileId", "SessionId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_CoachPlanRevision_UserProfileId_SessionId_RevisionNumber");

                    b.ToTable("CoachPlanRevision", (string)null);
                });

            modelBuilder.Entity("SentenceStudio.Api.Coach.Persistence.CoachSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActiveConstraintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AgentConfigVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentImplementation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ClarificationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PendingSuggestionCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingSuggestionDeltaJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("PendingSuggestionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProtectedAgentSession")
                        .HasColumnType("text");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<int>("SessionSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StopReason")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_CoachSession_ExpiresAt");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_CoachSession_UserProfileId");

                    b.HasIndex("UserProfileId", "Status")
                        .HasDatabaseName("IX_CoachSession_UserProfileId_Status");

                    b.ToTable("CoachSession", (string)null);
                });

            modelBuilder.Entity("SentenceStudio.Api.Coach.Persistence.CoachUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("RunCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WeekKey")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "LocalDate")
                        .IsUnique()
                        .HasDatabaseName("IX_CoachUsage_UserProfileId_LocalDate");

                    b.HasIndex("UserProfileId", "WeekKey")
                        .HasDatabaseName("IX_CoachUsage_UserProfileId_WeekKey");

                    b.ToTable("CoachUsage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
