using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SentenceStudio.Api.Feedback.Persistence;

/// <summary>
/// Server-only PostgreSQL context for the feedback submission ledger and its rate windows.
/// </summary>
/// <remarks>
/// <para>
/// Deliberately separate from <c>ApplicationDbContext</c>, for the same three reasons the coach
/// context is:
/// </para>
/// <list type="bullet">
/// <item>
/// These rows never sync to a device. Adding them to <c>ApplicationDbContext</c> would enrol them
/// in CoreSync, which provisions change-tracking for everything it owns — so a learner's device
/// would begin replicating a server-side rate limiter.
/// </item>
/// <item>
/// <c>ApplicationDbContext</c> is dual-provider and every migration added to it needs a
/// hand-written SQLite twin carrying <c>[DbContext]</c> and <c>[Migration]</c> attributes or it is
/// silently skipped on mobile. This schema has no business existing on a phone at all, so the
/// correct number of SQLite twins is zero and the way to guarantee zero is to not be in that
/// context.
/// </item>
/// <item>
/// Its retention rule is its own: submission rows age out on a feedback-specific window that has
/// nothing to do with how long learning data is kept.
/// </item>
/// </list>
/// <para>
/// It carries its own <c>__FeedbackMigrationsHistory</c> table (configured at registration), so
/// this migration set and the application's never see each other's rows and either can be applied
/// independently.
/// </para>
/// <para>
/// <c>PendingModelChangesWarning</c> is <b>not</b> suppressed for this context, anywhere. The
/// schema is single-provider and its migrations are hand-checked, so drift is a defect rather than
/// a known state to live with — and suppression is how drift reaches production silently.
/// <c>FeedbackModelMigrationParityTests</c> asserts the same thing without a server, so the answer
/// arrives while the model change is still on screen.
/// </para>
/// </remarks>
public sealed class FeedbackDbContext : DbContext
{
    public FeedbackDbContext(DbContextOptions<FeedbackDbContext> options) : base(options)
    {
    }

    /// <summary>One row per redeemable preview; the exactly-once ledger.</summary>
    public DbSet<FeedbackSubmission> FeedbackSubmissions => Set<FeedbackSubmission>();

    /// <summary>One row per (owner, limit); the durable rate windows.</summary>
    public DbSet<FeedbackRateWindow> FeedbackRateWindows => Set<FeedbackRateWindow>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<FeedbackSubmission>(entity =>
        {
            entity.ToTable("FeedbackSubmission");

            // The key is the token nonce, assigned by the server at preview time and never
            // generated by the database. The claim is an INSERT of this exact value, so a
            // database-generated key would defeat the entire mechanism.
            entity.HasKey(e => e.Jti);
            entity.Property(e => e.Jti).ValueGeneratedNever()
                  .HasMaxLength(FeedbackPreviewToken.MaxJtiLength);

            entity.Property(e => e.UserProfileId).IsRequired().HasMaxLength(64);
            entity.Property(e => e.Status).HasConversion<int>();
            entity.Property(e => e.ContentDigest).IsRequired().HasMaxLength(64);

            entity.Property(e => e.IssueUrl).HasMaxLength(512);
            entity.Property(e => e.IssueTitle).HasMaxLength(FeedbackPreviewToken.MaxTitleLength);
            entity.Property(e => e.FailureCode).HasMaxLength(64);

            entity.Property(e => e.RouteCategory).HasConversion<int>();
            entity.Property(e => e.Platform).HasConversion<int>();
            entity.Property(e => e.AppVersion).IsRequired()
                  .HasMaxLength(FeedbackClientMetadataNormalizer.MaxVersionLength);

            // Erasure and per-owner reads go through this.
            entity.HasIndex(e => e.UserProfileId)
                  .HasDatabaseName("IX_FeedbackSubmission_UserProfileId");

            // Retention prunes on token expiry, so it must not be a sequential scan.
            entity.HasIndex(e => e.TokenExpiresAtUtc)
                  .HasDatabaseName("IX_FeedbackSubmission_TokenExpiresAtUtc");

            // Operator reconciliation reads the in-doubt rows: "which submissions may have created
            // an issue nobody has a link to?"
            entity.HasIndex(e => e.Status)
                  .HasDatabaseName("IX_FeedbackSubmission_Status");
        });

        modelBuilder.Entity<FeedbackRateWindow>(entity =>
        {
            entity.ToTable("FeedbackRateWindow");

            // Composite key, so the "insert the first event for this owner" path is itself
            // arbitrated by the database: two replicas racing to create the same window row
            // resolve to one insert and one unique violation, which the limiter retries as a read.
            entity.HasKey(e => new { e.UserProfileId, e.Kind });
            entity.Property(e => e.UserProfileId).HasMaxLength(64);
            entity.Property(e => e.Kind).HasConversion<int>();

            // Bounded by the limit, which the options validator caps. 512 holds the ceiling of 60
            // preview stamps with room to spare.
            entity.Property(e => e.RecentTicksCsv).IsRequired().HasMaxLength(512);

            entity.HasIndex(e => e.UpdatedAtUtc)
                  .HasDatabaseName("IX_FeedbackRateWindow_UpdatedAtUtc");
        });

        PinTimestampsToUtc(modelBuilder);
    }

    /// <summary>
    /// Pins every <see cref="DateTime"/> to <c>timestamp with time zone</c> and normalises it to
    /// UTC in both directions.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The API host sets <c>Npgsql.EnableLegacyTimestampBehavior</c> process-wide, for the
    /// SQLite-era values in <c>ApplicationDbContext</c>. That switch is global, so it applies to
    /// this context too, and it does two things this schema cannot tolerate.
    /// </para>
    /// <para>
    /// It remaps <see cref="DateTime"/> to <c>timestamp without time zone</c>, which is not what
    /// the migration created — so without the pin the runtime model disagrees with its own
    /// migration and every insert fails on a type mismatch. And it materialises a
    /// <c>timestamp with time zone</c> into the host's local zone with
    /// <see cref="DateTimeKind.Local"/>. The instant survives; comparisons do not, because
    /// <see cref="DateTime"/> operators ignore <see cref="DateTime.Kind"/> and compare ticks.
    /// </para>
    /// <para>
    /// Both stored timestamps here are compared against an in-memory
    /// <c>TimeProvider.GetUtcNow().UtcDateTime</c>, and both comparisons are load-bearing. A
    /// retention sweep reading <see cref="FeedbackSubmission.TokenExpiresAtUtc"/> shifted by the
    /// host's offset would delete ledger rows early — which is the exactly-once guarantee lapsing —
    /// and a rate window whose <see cref="FeedbackRateWindow.UpdatedAtUtc"/> is shifted would be
    /// pruned early, handing an owner a fresh allowance. A deployment running in UTC hides both,
    /// which is precisely why this is pinned at the model rather than at each comparison.
    /// </para>
    /// </remarks>
    private void PinTimestampsToUtc(ModelBuilder modelBuilder)
    {
        if (!Database.IsNpgsql())
        {
            return;
        }

        foreach (var property in modelBuilder.Model.GetEntityTypes()
                     .SelectMany(t => t.GetProperties())
                     .Where(p => p.ClrType == typeof(DateTime) || p.ClrType == typeof(DateTime?)))
        {
            property.SetColumnType("timestamp with time zone");
            property.SetValueConverter(UtcDateTimeConverter);
        }
    }

    private static readonly ValueConverter<DateTime, DateTime> UtcDateTimeConverter = new(
        value => value.Kind == DateTimeKind.Unspecified
            ? DateTime.SpecifyKind(value, DateTimeKind.Utc)
            : value.ToUniversalTime(),
        value => value.Kind == DateTimeKind.Unspecified
            ? DateTime.SpecifyKind(value, DateTimeKind.Utc)
            : value.ToUniversalTime());
}
