using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using YoutubeExplode;
using YoutubeExplode.Videos.Streams;
using YoutubeExplode.Videos.ClosedCaptions;

namespace SentenceStudio.Services;

/// <summary>
/// Structured exception for YouTube import failures with a classifiable error code.
/// User-facing <see cref="Exception.Message"/> is sanitized (no video IDs or URLs).
/// The original provider exception is preserved as <see cref="Exception.InnerException"/>
/// for server-side diagnostics.
/// </summary>
public class VideoImportException : Exception
{
    /// <summary>Classification code for the import failure (for example, VideoUnavailable or RateLimited).</summary>
    public string ErrorCode { get; }

    public VideoImportException(string message, string errorCode, Exception? innerException = null)
        : base(message, innerException)
    {
        ErrorCode = errorCode;
    }
}

/// <summary>
/// Abstraction over <see cref="YouTubeImportService"/> for testability.
/// The pipeline and its unit tests depend on this interface, not the concrete type.
/// </summary>
public interface IYouTubeImportService
{
    Task<YoutubeExplode.Videos.Video> GetVideoMetadataAsync(string videoUrl);
    Task<List<TranscriptTrack>> GetAvailableTranscriptsAsync(string videoUrl);
    Task<string> DownloadTranscriptTextAsync(TranscriptTrack track);
    Task<StreamHistory> ExtractAudioClipAsync(string videoUrl, double startTime, double duration);
}

public class TranscriptTrack
{
    public string LanguageCode { get; set; } = string.Empty;
    public string LanguageName { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
    public ClosedCaptionTrackInfo TrackInfo { get; set; }
}

public class YouTubeImportService : IYouTubeImportService
{
    private readonly YoutubeClient _youtubeClient;
    private readonly AudioAnalyzer _audioAnalyzer;

    public YouTubeImportService(AudioAnalyzer audioAnalyzer)
    {
        _youtubeClient = new YoutubeClient();
        _audioAnalyzer = audioAnalyzer;
    }

    /// <inheritdoc />
    public async Task<StreamHistory> ExtractAudioClipAsync(
        string videoUrl,
        double startTime,
        double duration)
    {
        try
        {
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var video = await _youtubeClient.Videos.GetAsync(videoId);
            var streamManifest = await _youtubeClient.Videos.Streams.GetManifestAsync(videoId);

            var audioStreamInfo = streamManifest
                .GetAudioOnlyStreams()
                .Where(s => s.AudioCodec.StartsWith("mp4", StringComparison.OrdinalIgnoreCase))
                .GetWithHighestBitrate();

            if (audioStreamInfo == null)
                throw new VideoImportException(
                    "No suitable audio stream found for this video.",
                    "NoAudioStream");

            var fullAudioStream = await _youtubeClient.Videos.Streams.GetAsync(audioStreamInfo);
            var clippedAudioStream = new MemoryStream();

            fullAudioStream.Position = 0;
            var waveformData = await _audioAnalyzer.GetWaveformAsync(fullAudioStream, 1200);
            fullAudioStream.Position = 0;

            return new StreamHistory
            {
                FileName = $"youtube_clip_{startTime}_{duration}.wav",
                Title = video.Title,
                Source = "YouTube",
                SourceUrl = videoUrl,
                Duration = duration,
                WaveformData = waveformData,
                Stream = clippedAudioStream
            };
        }
        catch (OperationCanceledException) { throw; }
        catch (VideoImportException) { throw; }
        catch (YoutubeExplode.Exceptions.VideoUnavailableException ex)
        {
            throw ClassifyVideoUnavailable(ex);
        }
        catch (YoutubeExplode.Exceptions.RequestLimitExceededException ex)
        {
            throw ClassifyRateLimited(ex);
        }
        catch (HttpRequestException ex)
        {
            throw ClassifyNetwork(ex);
        }
        catch (Exception ex)
        {
            throw new VideoImportException(
                "An unexpected error occurred while extracting audio.",
                "Unknown", ex);
        }
    }

    /// <inheritdoc />
    public async Task<List<TranscriptTrack>> GetAvailableTranscriptsAsync(string videoUrl)
    {
        try
        {
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var trackManifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(videoId);

            var tracks = new List<TranscriptTrack>();
            foreach (var trackInfo in trackManifest.Tracks)
            {
                tracks.Add(new TranscriptTrack
                {
                    LanguageCode = trackInfo.Language.Code,
                    LanguageName = trackInfo.Language.Name,
                    IsAutoGenerated = trackInfo.IsAutoGenerated,
                    TrackInfo = trackInfo
                });
            }

            return tracks;
        }
        catch (OperationCanceledException) { throw; }
        catch (VideoImportException) { throw; }
        catch (YoutubeExplode.Exceptions.VideoUnavailableException ex)
        {
            throw ClassifyVideoUnavailable(ex);
        }
        catch (YoutubeExplode.Exceptions.RequestLimitExceededException ex)
        {
            throw ClassifyRateLimited(ex);
        }
        catch (HttpRequestException ex)
        {
            throw ClassifyNetwork(ex);
        }
        catch (Exception ex)
        {
            throw new VideoImportException(
                "An unexpected error occurred while fetching transcripts.",
                "Unknown", ex);
        }
    }

    /// <inheritdoc />
    public async Task<string> DownloadTranscriptTextAsync(TranscriptTrack track)
    {
        try
        {
            var closedCaptionTrack = await _youtubeClient.Videos.ClosedCaptions.GetAsync(track.TrackInfo);

            var transcriptBuilder = new System.Text.StringBuilder();
            foreach (var caption in closedCaptionTrack.Captions)
            {
                transcriptBuilder.AppendLine(caption.Text);
            }

            return transcriptBuilder.ToString();
        }
        catch (OperationCanceledException) { throw; }
        catch (VideoImportException) { throw; }
        catch (YoutubeExplode.Exceptions.VideoUnavailableException ex)
        {
            throw ClassifyVideoUnavailable(ex);
        }
        catch (YoutubeExplode.Exceptions.RequestLimitExceededException ex)
        {
            throw ClassifyRateLimited(ex);
        }
        catch (HttpRequestException ex)
        {
            throw ClassifyNetwork(ex);
        }
        catch (Exception ex)
        {
            throw new VideoImportException(
                "An unexpected error occurred while downloading transcript.",
                "Unknown", ex);
        }
    }

    /// <inheritdoc />
    public async Task<YoutubeExplode.Videos.Video> GetVideoMetadataAsync(string videoUrl)
    {
        try
        {
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            return await _youtubeClient.Videos.GetAsync(videoId);
        }
        catch (OperationCanceledException) { throw; }
        catch (VideoImportException) { throw; }
        catch (YoutubeExplode.Exceptions.VideoUnavailableException ex)
        {
            throw ClassifyVideoUnavailable(ex);
        }
        catch (YoutubeExplode.Exceptions.RequestLimitExceededException ex)
        {
            throw ClassifyRateLimited(ex);
        }
        catch (HttpRequestException ex)
        {
            throw ClassifyNetwork(ex);
        }
        catch (Exception ex)
        {
            throw new VideoImportException(
                "An unexpected error occurred while fetching video metadata.",
                "Unknown", ex);
        }
    }

    // ────────── Shared classifiers (no video ID / URL in user-facing message) ──────────

    private static VideoImportException ClassifyVideoUnavailable(
        YoutubeExplode.Exceptions.VideoUnavailableException ex) =>
        new("This video is not accessible. It may be private, age-restricted, region-locked, or removed.",
            "VideoUnavailable", ex);

    private static VideoImportException ClassifyRateLimited(
        YoutubeExplode.Exceptions.RequestLimitExceededException ex) =>
        new("YouTube is temporarily rate-limiting requests. Please wait a few minutes and try again.",
            "RateLimited", ex);

    private static VideoImportException ClassifyNetwork(HttpRequestException ex) =>
        new(ex.StatusCode is { } statusCode
                ? $"Could not reach YouTube (HTTP {(int)statusCode}). Please try again later."
                : "Could not reach YouTube. Please try again later.",
            "NetworkError", ex);
}