// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SentenceStudio.Api.Feedback.Persistence;

#nullable disable

namespace SentenceStudio.Api.Feedback.Persistence.Migrations
{
    [DbContext(typeof(FeedbackDbContext))]
    partial class FeedbackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SentenceStudio.Api.Feedback.Persistence.FeedbackRateWindow", b =>
                {
                    b.Property<string>("UserProfileId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("RecentTicksCsv")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserProfileId", "Kind");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_FeedbackRateWindow_UpdatedAtUtc");

                    b.ToTable("FeedbackRateWindow", (string)null);
                });

            modelBuilder.Entity("SentenceStudio.Api.Feedback.Persistence.FeedbackSubmission", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("integer");

                    b.Property<string>("IssueTitle")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IssueUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int>("RouteCategory")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Jti");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FeedbackSubmission_Status");

                    b.HasIndex("TokenExpiresAtUtc")
                        .HasDatabaseName("IX_FeedbackSubmission_TokenExpiresAtUtc");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_FeedbackSubmission_UserProfileId");

                    b.ToTable("FeedbackSubmission", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
