using System.Globalization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using SentenceStudio.Contracts.Plans;
using SentenceStudio.Data;
using SentenceStudio.Services.Plans;
using SentenceStudio.Services.Progress;
using SentenceStudio.Shared.Models;

namespace SentenceStudio.Api.Plans;

/// <summary>
/// <c>POST /api/v1/plans/adhoc/start</c> — starts (or idempotently resumes) an
/// ad-hoc activity-tracking session. The synthetic <c>planItemId</c> is
/// deterministic from <c>clientSessionId</c> (<c>adhoc-{clientSessionId}</c>),
/// which gives durable idempotency without a schema change: the existing
/// <c>(UserProfileId, Date, PlanItemId)</c> uniqueness contract on
/// <c>DailyPlanCompletion</c> covers replay protection.
///
/// MAUI's <c>ProgressService.StartAdHocSessionAsync</c> continues to generate
/// <c>adhoc-{Guid.NewGuid()}</c> for local-only flows and is unaffected.
/// </summary>
public static class AdhocPlanEndpoints
{
    /// <summary>Default when the client omits <c>estimatedMinutes</c>. Matches
    /// the MAUI <see cref="SentenceStudio.Services.Progress.IProgressService.StartAdHocSessionAsync"/> default.</summary>
    public const int DefaultEstimatedMinutes = 10;

    /// <summary>Upper clamp to mirror plan endpoint validation. Aligns with
    /// <c>PlanService.MaxMinutesSpent</c> so an ad-hoc row can't blow past the
    /// progress endpoint's clamp anyway.</summary>
    public const int MaxEstimatedMinutes = 24 * 60;

    public static IEndpointRouteBuilder MapAdhocPlan(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/v1/plans/adhoc/start", StartAdhocAsync)
            .WithName("StartAdhocSession")
            .RequireAuthorization();
        return app;
    }

    private static async Task<IResult> StartAdhocAsync(
        AdhocStartRequest? request,
        IUserScopeProvider userScope,
        ApplicationDbContext db,
        ILoggerFactory loggerFactory,
        CancellationToken ct)
    {
        var logger = loggerFactory.CreateLogger("AdhocPlan");

        if (request is null)
        {
            return Results.Problem(
                title: "Missing request body",
                detail: "Request body is required.",
                statusCode: StatusCodes.Status400BadRequest);
        }

        if (string.IsNullOrWhiteSpace(request.ClientSessionId) ||
            !Guid.TryParse(request.ClientSessionId, out var clientSessionGuid))
        {
            return Results.Problem(
                title: "Invalid clientSessionId",
                detail: "'clientSessionId' must be a non-empty UUID generated by the client.",
                statusCode: StatusCodes.Status400BadRequest);
        }

        if (string.IsNullOrWhiteSpace(request.ActivityType) ||
            !Enum.TryParse<PlanActivityType>(request.ActivityType, ignoreCase: false, out var activityType) ||
            !Enum.IsDefined(typeof(PlanActivityType), activityType))
        {
            return Results.Problem(
                title: "Invalid activityType",
                detail: "'activityType' must be a valid PlanActivityType (e.g. Reading, Writing, Translation, ...).",
                statusCode: StatusCodes.Status400BadRequest);
        }

        var estimatedMinutes = request.EstimatedMinutes ?? DefaultEstimatedMinutes;
        if (estimatedMinutes <= 0)
        {
            return Results.Problem(
                title: "Invalid estimatedMinutes",
                detail: "'estimatedMinutes' must be a positive integer.",
                statusCode: StatusCodes.Status400BadRequest);
        }
        if (estimatedMinutes > MaxEstimatedMinutes)
        {
            // Clamp on the upper bound rather than rejecting — matches the
            // progress endpoint's clamp-rather-than-reject behaviour.
            estimatedMinutes = MaxEstimatedMinutes;
        }

        if (!userScope.TryGetUserProfileId(out var userProfileId) || string.IsNullOrEmpty(userProfileId))
        {
            return Results.Unauthorized();
        }

        // Deterministic id makes the operation idempotent end-to-end: the
        // primary uniqueness check is the lookup below, and even a race
        // between two replays would only collide on the same row.
        var planItemId = $"adhoc-{clientSessionGuid:D}";
        var today = DateTime.UtcNow.Date;

        try
        {
            var existing = await db.DailyPlanCompletions
                .FirstOrDefaultAsync(c => c.UserProfileId == userProfileId
                                          && c.Date == today
                                          && c.PlanItemId == planItemId, ct);

            if (existing is not null)
            {
                logger.LogInformation("🔁 Ad-hoc replay for client session {ClientSessionId} → {PlanItemId}",
                    clientSessionGuid, planItemId);
                return Results.Ok(BuildResponse(existing, activityType, estimatedMinutes));
            }

            var completion = new DailyPlanCompletion
            {
                Id = Guid.NewGuid().ToString(),
                UserProfileId = userProfileId,
                Date = today,
                PlanItemId = planItemId,
                ActivityType = activityType.ToString(),
                ResourceId = request.ResourceId,
                SkillId = request.SkillId,
                IsCompleted = false,
                CompletedAt = null,
                MinutesSpent = 0,
                EstimatedMinutes = estimatedMinutes,
                Priority = 999, // sort after planned items, mirrors ProgressService.StartAdHocSessionAsync
                TitleKey = $"Activity_{activityType}",
                DescriptionKey = string.Empty,
                Rationale = string.Empty,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
            };

            db.DailyPlanCompletions.Add(completion);
            try
            {
                await db.SaveChangesAsync(ct);
            }
            catch (DbUpdateException ex) when (IsUniqueViolation(ex))
            {
                // Lost a race with a concurrent replay — fetch the winner and
                // return 200 as if we were the duplicate caller.
                db.Entry(completion).State = EntityState.Detached;
                var winner = await db.DailyPlanCompletions
                    .FirstAsync(c => c.UserProfileId == userProfileId
                                     && c.Date == today
                                     && c.PlanItemId == planItemId, ct);
                logger.LogInformation("🔁 Ad-hoc replay (race) for client session {ClientSessionId} → {PlanItemId}",
                    clientSessionGuid, planItemId);
                return Results.Ok(BuildResponse(winner, activityType, estimatedMinutes));
            }

            logger.LogInformation("🎯 Started ad-hoc session {PlanItemId} for {ActivityType} (user={UserProfileId})",
                planItemId, activityType, userProfileId);

            return Results.Created($"/api/v1/plans/{today:yyyy-MM-dd}/items/{planItemId}/progress",
                BuildResponse(completion, activityType, estimatedMinutes));
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "POST /api/v1/plans/adhoc/start failed");
            return Results.Problem(
                detail: "Failed to start ad-hoc session.",
                statusCode: StatusCodes.Status500InternalServerError);
        }
    }

    private static AdhocStartResponse BuildResponse(
        DailyPlanCompletion row,
        PlanActivityType activityType,
        int requestedEstimatedMinutes)
    {
        // On replay, prefer the row's stored EstimatedMinutes (the first call
        // is the source of truth for the session). On insert these are equal.
        return new AdhocStartResponse
        {
            PlanItemId = row.PlanItemId,
            ActivityType = activityType.ToString(),
            Date = row.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
            EstimatedMinutes = row.EstimatedMinutes > 0 ? row.EstimatedMinutes : requestedEstimatedMinutes,
        };
    }

    private static bool IsUniqueViolation(DbUpdateException ex)
    {
        // SQLite: "UNIQUE constraint failed". Postgres: SqlState 23505.
        // We treat any inner-exception message containing "unique" as a
        // best-effort hint — sufficient because we only get here if the
        // primary-key Id collides (very unlikely) OR a unique index is added
        // on (UserProfileId, Date, PlanItemId) later.
        var message = ex.InnerException?.Message ?? ex.Message;
        return message.Contains("UNIQUE", StringComparison.OrdinalIgnoreCase)
               || message.Contains("23505", StringComparison.Ordinal);
    }
}
