global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using MauiIcons.Core;
global using MauiIcons.SegoeFluent;
global using Scriban;
global using SentenceStudio.Messages;
global using SentenceStudio.Shared.Models;
global using SentenceStudio.Services;
global using SentenceStudio.Data;
global using SentenceStudio.Resources.Styles;
global using System.Diagnostics;
global using SQLite;
global using SentenceStudio.Common;
global using SQLiteNetExtensions.Attributes;
global using SentenceStudio.Pages.Controls;
global using MauiReactor;
global using MauiControls = Microsoft.Maui.Controls;