global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using CommunityToolkit.Maui.Converters;
global using CommunityToolkit.Maui.Extensions;
global using CommunityToolkit.Maui.Markup;
global using MauiIcons.Core;
global using MauiIcons.SegoeFluent;
global using Scriban;
global using SentenceStudio.Messages;
global using SentenceStudio.Models;
global using SentenceStudio.Services;
global using SentenceStudio.Data;
global using Sharpnado.Tasks;
global using System.Diagnostics;
global using SQLite;
global using SentenceStudio.Common;
global using SQLiteNetExtensions;
global using SQLiteNetExtensions.Extensions;
global using SQLiteNetExtensions.Attributes;
global using Microsoft.Maui.Controls.Shapes;
global using SentenceStudio.Pages.Controls;
global using static CommunityToolkit.Maui.Markup.GridRowsColumns;
global using static Microsoft.Maui.Controls.VisualStateManager;
