//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentenceStudio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentenceStudio.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Vocabulary List.
        /// </summary>
        internal static string AddVocabularyList {
            get {
                return ResourceManager.GetString("AddVocabularyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Studio.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a vocabulary word.
        /// </summary>
        internal static string ChooseAVocabularyWord {
            get {
                return ResourceManager.GetString("ChooseAVocabularyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clozures.
        /// </summary>
        internal static string Clozures {
            get {
                return ResourceManager.GetString("Clozures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like me to create a starter vocabulary list for you?.
        /// </summary>
        internal static string CreateStarterVocabPrompt {
            get {
                return ResourceManager.GetString("CreateStarterVocabPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Skill Profile.
        /// </summary>
        internal static string DefaultSkill {
            get {
                return ResourceManager.GetString("DefaultSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Vocabulary.
        /// </summary>
        internal static string DefaultVocabulary {
            get {
                return ResourceManager.GetString("DefaultVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe a Scene.
        /// </summary>
        internal static string DescribeAScene {
            get {
                return ResourceManager.GetString("DescribeAScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayLanguage.
        /// </summary>
        internal static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluency.
        /// </summary>
        internal static string Fluency {
            get {
                return ResourceManager.GetString("Fluency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Do You Say.
        /// </summary>
        internal static string HowDoYouSay {
            get {
                return ResourceManager.GetString("HowDoYouSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see....
        /// </summary>
        internal static string ISee {
            get {
                return ResourceManager.GetString("ISee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        internal static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Language.
        /// </summary>
        internal static string NativeLanguage {
            get {
                return ResourceManager.GetString("NativeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I&apos;ll do it myself.
        /// </summary>
        internal static string NoVocabPromptResponse {
            get {
                return ResourceManager.GetString("NoVocabPromptResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string OpenAI_APIKey {
            get {
                return ResourceManager.GetString("OpenAI_APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse a Sentence.
        /// </summary>
        internal static string ParseASentence {
            get {
                return ResourceManager.GetString("ParseASentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Practice.
        /// </summary>
        internal static string PracticeWriting {
            get {
                return ResourceManager.GetString("PracticeWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wrote.
        /// </summary>
        internal static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowing.
        /// </summary>
        internal static string Shadowing {
            get {
                return ResourceManager.GetString("Shadowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Profiles.
        /// </summary>
        internal static string SkillProfiles {
            get {
                return ResourceManager.GetString("SkillProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a Lesson.
        /// </summary>
        internal static string StartLesson {
            get {
                return ResourceManager.GetString("StartLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Teller.
        /// </summary>
        internal static string Storyteller {
            get {
                return ResourceManager.GetString("Storyteller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string TitleDashboard {
            get {
                return ResourceManager.GetString("TitleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you say that in Korean?.
        /// </summary>
        internal static string UserInputPlaceholder {
            get {
                return ResourceManager.GetString("UserInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary.
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary List.
        /// </summary>
        internal static string VocabularyList {
            get {
                return ResourceManager.GetString("VocabularyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        internal static string Warmup {
            get {
                return ResourceManager.GetString("Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you see?.
        /// </summary>
        internal static string WhatDoYouSee {
            get {
                return ResourceManager.GetString("WhatDoYouSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to say?.
        /// </summary>
        internal static string WhatDoYouWantToSay {
            get {
                return ResourceManager.GetString("WhatDoYouWantToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
