//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentenceStudio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentenceStudio.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Resource.
        /// </summary>
        internal static string AddResource {
            get {
                return ResourceManager.GetString("AddResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Vocabulary List.
        /// </summary>
        internal static string AddVocabularyList {
            get {
                return ResourceManager.GetString("AddVocabularyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Word.
        /// </summary>
        internal static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You matched all vocabulary pairs!.
        /// </summary>
        internal static string AllPairsMatched {
            get {
                return ResourceManager.GetString("AllPairsMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Studio.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string AudioTime {
            get {
                return ResourceManager.GetString("AudioTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking match....
        /// </summary>
        internal static string CheckingMatch {
            get {
                return ResourceManager.GetString("CheckingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a vocabulary word.
        /// </summary>
        internal static string ChooseAVocabularyWord {
            get {
                return ResourceManager.GetString("ChooseAVocabularyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        internal static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clozures.
        /// </summary>
        internal static string Clozures {
            get {
                return ResourceManager.GetString("Clozures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard!.
        /// </summary>
        internal static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like me to create a starter vocabulary list for you?.
        /// </summary>
        internal static string CreateStarterVocabPrompt {
            get {
                return ResourceManager.GetString("CreateStarterVocabPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Skill Profile.
        /// </summary>
        internal static string DefaultSkill {
            get {
                return ResourceManager.GetString("DefaultSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Vocabulary.
        /// </summary>
        internal static string DefaultVocabulary {
            get {
                return ResourceManager.GetString("DefaultVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe a Scene.
        /// </summary>
        internal static string DescribeAScene {
            get {
                return ResourceManager.GetString("DescribeAScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details &gt;.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayLanguage.
        /// </summary>
        internal static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading vocabulary. Please try again..
        /// </summary>
        internal static string ErrorLoadingVocabulary {
            get {
                return ResourceManager.GetString("ErrorLoadingVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exported successfully!.
        /// </summary>
        internal static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all your learning data as CSV files in a ZIP archive. This includes vocabulary, progress, and settings..
        /// </summary>
        internal static string ExportDataDescription {
            get {
                return ResourceManager.GetString("ExportDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluency.
        /// </summary>
        internal static string Fluency {
            get {
                return ResourceManager.GetString("Fluency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great match! 🎉.
        /// </summary>
        internal static string GreatMatch {
            get {
                return ResourceManager.GetString("GreatMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Do You Say.
        /// </summary>
        internal static string HowDoYouSay {
            get {
                return ResourceManager.GetString("HowDoYouSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see....
        /// </summary>
        internal static string ISee {
            get {
                return ResourceManager.GetString("ISee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Voices.
        /// </summary>
        internal static string KoreanVoices {
            get {
                return ResourceManager.GetString("KoreanVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Resources.
        /// </summary>
        internal static string LearningResources {
            get {
                return ResourceManager.GetString("LearningResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        internal static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading vocabulary....
        /// </summary>
        internal static string LoadingVocabulary {
            get {
                return ResourceManager.GetString("LoadingVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched: {0} / {1}    Misses: {2}.
        /// </summary>
        internal static string MatchedAndMisses {
            get {
                return ResourceManager.GetString("MatchedAndMisses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the vocabulary pairs!.
        /// </summary>
        internal static string MatchPairs {
            get {
                return ResourceManager.GetString("MatchPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        internal static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media URL.
        /// </summary>
        internal static string MediaURL {
            get {
                return ResourceManager.GetString("MediaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should I call you?.
        /// </summary>
        internal static string NameQuestion {
            get {
                return ResourceManager.GetString("NameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Language.
        /// </summary>
        internal static string NativeLanguage {
            get {
                return ResourceManager.GetString("NativeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Conversation.
        /// </summary>
        internal static string NewConversation {
            get {
                return ResourceManager.GetString("NewConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the next screen, you will be able to choose from a variety of activities to practice your language skills. Along the way Sentence Studio will keep track of your progress and report your growth..
        /// </summary>
        internal static string NextScreenDescription {
            get {
                return ResourceManager.GetString("NextScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a match. Try again!.
        /// </summary>
        internal static string NotAMatch {
            get {
                return ResourceManager.GetString("NotAMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I&apos;ll do it myself.
        /// </summary>
        internal static string NoVocabPromptResponse {
            get {
                return ResourceManager.GetString("NoVocabPromptResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vocabulary available. Please add words to your vocabulary list..
        /// </summary>
        internal static string NoVocabularyAvailable {
            get {
                return ResourceManager.GetString("NoVocabularyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string OpenAI_APIKey {
            get {
                return ResourceManager.GetString("OpenAI_APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse a Sentence.
        /// </summary>
        internal static string ParseASentence {
            get {
                return ResourceManager.GetString("ParseASentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Again.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Practice.
        /// </summary>
        internal static string PracticeWriting {
            get {
                return ResourceManager.GetString("PracticeWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Device.
        /// </summary>
        internal static string SaveToDevice {
            get {
                return ResourceManager.GetString("SaveToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another tile to make a match!.
        /// </summary>
        internal static string SelectAnotherTile {
            get {
                return ResourceManager.GetString("SelectAnotherTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wrote.
        /// </summary>
        internal static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowing.
        /// </summary>
        internal static string Shadowing {
            get {
                return ResourceManager.GetString("Shadowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Profiles.
        /// </summary>
        internal static string SkillProfiles {
            get {
                return ResourceManager.GetString("SkillProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a Lesson.
        /// </summary>
        internal static string StartLesson {
            get {
                return ResourceManager.GetString("StartLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Teller.
        /// </summary>
        internal static string Storyteller {
            get {
                return ResourceManager.GetString("Storyteller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (comma separated).
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string TitleDashboard {
            get {
                return ResourceManager.GetString("TitleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        internal static string Transcript {
            get {
                return ResourceManager.GetString("Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated:.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you say that in Korean?.
        /// </summary>
        internal static string UserInputPlaceholder {
            get {
                return ResourceManager.GetString("UserInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary.
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary List.
        /// </summary>
        internal static string VocabularyList {
            get {
                return ResourceManager.GetString("VocabularyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary Matching.
        /// </summary>
        internal static string VocabularyMatchingTitle {
            get {
                return ResourceManager.GetString("VocabularyMatchingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do-Hyeon.
        /// </summary>
        internal static string VoiceDohyeon {
            get {
                return ResourceManager.GetString("VoiceDohyeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male - Older, mature.
        /// </summary>
        internal static string VoiceDohyeonDesc {
            get {
                return ResourceManager.GetString("VoiceDohyeonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyun-Bin.
        /// </summary>
        internal static string VoiceHyunbin {
            get {
                return ResourceManager.GetString("VoiceHyunbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male - Cool, professional.
        /// </summary>
        internal static string VoiceHyunbinDesc {
            get {
                return ResourceManager.GetString("VoiceHyunbinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jennie.
        /// </summary>
        internal static string VoiceJennie {
            get {
                return ResourceManager.GetString("VoiceJennie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female - Youthful, professional.
        /// </summary>
        internal static string VoiceJennieDesc {
            get {
                return ResourceManager.GetString("VoiceJennieDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jina.
        /// </summary>
        internal static string VoiceJina {
            get {
                return ResourceManager.GetString("VoiceJina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female - Mid-aged, news broadcaster.
        /// </summary>
        internal static string VoiceJinaDesc {
            get {
                return ResourceManager.GetString("VoiceJinaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ji-Young.
        /// </summary>
        internal static string VoiceJiyoung {
            get {
                return ResourceManager.GetString("VoiceJiyoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female - Warm, clear.
        /// </summary>
        internal static string VoiceJiyoungDesc {
            get {
                return ResourceManager.GetString("VoiceJiyoungDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yohan Koo.
        /// </summary>
        internal static string VoiceYohankoo {
            get {
                return ResourceManager.GetString("VoiceYohankoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male - Confident, authoritative.
        /// </summary>
        internal static string VoiceYohankooDesc {
            get {
                return ResourceManager.GetString("VoiceYohankooDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuna.
        /// </summary>
        internal static string VoiceYuna {
            get {
                return ResourceManager.GetString("VoiceYuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female - Young, cheerful.
        /// </summary>
        internal static string VoiceYunaDesc {
            get {
                return ResourceManager.GetString("VoiceYunaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while checking your match....
        /// </summary>
        internal static string WaitCheckingMatch {
            get {
                return ResourceManager.GetString("WaitCheckingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        internal static string Warmup {
            get {
                return ResourceManager.GetString("Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sentence Studio!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strengthen your language skills with our fun and interactive sentence building activities..
        /// </summary>
        internal static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you see?.
        /// </summary>
        internal static string WhatDoYouSee {
            get {
                return ResourceManager.GetString("WhatDoYouSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to say?.
        /// </summary>
        internal static string WhatDoYouWantToSay {
            get {
                return ResourceManager.GetString("WhatDoYouWantToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
