name: "Copilot Setup Steps"
on: workflow_dispatch
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x
          10.x
        include-prerelease: true
    - name: Install MAUI workload
      run: |
        dotnet workload install maui-android
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build shared libraries
      run: |
        cd src
        dotnet build --no-restore src/SentenceStudio.Shared/SentenceStudio.Shared.csproj
        dotnet build --no-restore src/SentenceStudio.ServiceDefaults/SentenceStudio.ServiceDefaults.csproj
        dotnet build --no-restore src/SentenceStudio.WebServiceDefaults/SentenceStudio.WebServiceDefaults.csproj
    - name: Build web applications
      run: |
        cd src
        dotnet build --no-restore src/SentenceStudio.Web/SentenceStudio.Web.csproj
        dotnet build --no-restore src/SentenceStudio.AppHost/SentenceStudio.AppHost.csproj
    - name: Build MAUI project (Android)
      run: |
        cd src
        dotnet build --no-restore -f net10.0-android src/SentenceStudio/SentenceStudio.csproj
    - name: Environment verification
      run: |
        echo "✅ Development environment setup complete"
        echo "🔧 .NET versions installed:"
        dotnet --list-sdks
        echo "📦 Workloads installed:"
        dotnet workload list